# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: andresmen30/unipanamericana-docker
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

  deploy_to_droplet:
    runs-on: ubuntu-latest
    needs: build_and_push
    name: Deploy to Droplet
    steps:
      - name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 206.189.15.94
          username: root
          key: -----BEGIN OPENSSH PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
  NhAAAAAwEAAQAAAYEArG4aDyQWwmSYdMR6yE9dECQu0U232yLWgG/3tnSsl0yYbn2GTyRn
  ntC/V848wKgA0Eq+ycUbW9oKXF4CLaQZFkj6dnc7JH/tzA+rBxe4umDbpAdD8DYjpFZ4vL
  Eph8qqqU8GbwJjspxVs5+n0MhwMjkXvO9tYNzhU0a5K4ewOiB5//ew7KIW2f9yXDSEW3ds
  djd+rqu1bm6YeqdGYVWz8umLODnwiqQr7gQX4LeeFGWXORwTxDq1BjUHXQp7teA3gbvriI
  jXtNqenIOu7vmsxh3Tq1kzIIuoC7e5AWkvSvKmKZcx9b/h+rG745gAXaDSAYoHhd98Ay7H
  ij/3nE3QC2agObiUyUhIBAKloaOuu3TJhLEWB/qwQOSdNQfe2kwGsHrhidwq4DbR+Kpd6N
  m/s+/2YQuJNuFh72NZ1Gm3Cx7i2aiX2ZttRdoEswp7wzRmH+Ar6SEf0DJrfs4Fctrony8g
  jD1N7gFB/gg+C+3pL4ZS0PW5BV5mulxa6TJYI3vPAAAFkH/aTjh/2k44AAAAB3NzaC1yc2
  EAAAGBAKxuGg8kFsJkmHTEeshPXRAkLtFNt9si1oBv97Z0rJdMmG59hk8kZ57Qv1fOPMCo
  ANBKvsnFG1vaClxeAi2kGRZI+nZ3OyR/7cwPqwcXuLpg26QHQ/A2I6RWeLyxKYfKqqlPBm
  8CY7KcVbOfp9DIcDI5F7zvbWDc4VNGuSuHsDogef/3sOyiFtn/clw0hFt3bHY3fq6rtW5u
  mHqnRmFVs/Lpizg58IqkK+4EF+C3nhRllzkcE8Q6tQY1B10Ke7XgN4G764iI17TanpyDru
  75rMYd06tZMyCLqAu3uQFpL0rypimXMfW/4fqxu+OYAF2g0gGKB4XffAMux4o/95xN0Atm
  oDm4lMlISAQCpaGjrrt0yYSxFgf6sEDknTUH3tpMBrB64YncKuA20fiqXejZv7Pv9mELiT
  bhYe9jWdRptwse4tmol9mbbUXaBLMKe8M0Zh/gK+khH9Aya37OBXLa6J8vIIw9Te4BQf4I
  Pgvt6S+GUtD1uQVeZrpcWukyWCN7zwAAAAMBAAEAAAGBAJ8uIWZ65XvdzBR30fWbtokRLh
  tRCPsG5Ui6lM7eVPpz3oCZ5uSm8fXeNdZEcTdVoTKo3gp8qS4ZUtlEe/RQekxlYLr+hR3D
  7+4jRLsOfh2pDvsVLfXStQKgRWPElVdjlDsq1gCjDxCzXDavnAeVEmZ66FwmGC6Emor7Tj
  ROVjTDCH1x1uYNGNV1CcjvPoUF8Z4MyylLIPnqpV8Nj16J9M66JSjp7BLBTkCzjKuKNygT
  RRCWx/SuUbGCQOL2q5AShQdiowZ1UbJDm3RozAZ8yhzSuI4D8oGmIlMuxPx+97eKGamOLL
  ZALxSln0j9W3hpC/xcmgQW96uDqtdZPgB7jaFPKHpTndYuJZPOjbDk1TeCBJM2/Ey0453u
  FO3oxyoTzRXMY7P7uLBgP55Pzrmr1gXXHSBjSkCBQa6qda7nOtuiiOAk4V8RDgQoL5k2JP
  0WGlN9DkxpatT2Q0i+IuLtuq5Q5XIdX8SgmxIBhUU22MCA0sQEsmvh2D93ASv6yVIBWQAA
  AMB9YrCviVHbzdIJvWzJWnqSanx/Mpr2tP+oVkishVhVwmMuM/p77b2PBMAFe+MrumaZ2X
  wpOpt/5jz5wX14NySeeroW+3DXcqDlzoGPWB8/5j6tGvOUethnSGiCHRR9DW8mXmQ7TE6F
  rt1WPIEhUVW0pWEzQJ9Wx5rtocIyFtKhgKUZpelqKqtRXfVZpP0FnoU7jJxR/74sSdxt3R
  FcyaC3jgXgt8YtZ244qBLcAGqcERKpA7NkdxuL+5KYfcRrsRQAAADBANkQ2bMmgbgRh6mm
  piLx5hPkfsJexGAZ4VukxsgCmhzsszmlKKPngZOFCjYjLiTaDcRMiCSiL7L3NQQ2BAyLRz
  J8CzvFr0kAR8ZSsM6JYVQDI0Hghzcehxqc1OYt6r2lYV+hByWfoipaXxnIUA1SuFfkqj5E
  H9l7KOgv5/eCI2NDMaW6gYlvsl8fHo+B+WJntIWvYo5q5Jt/zYK+pMksGJ4OwSwttdP2c1
  Qg4xO/ootcO4kT83fvHgONs/M+tzikzQAAAMEAy1uvELf7T8tnxowuH+eZOlesSLXH/xyu
  Cwwco1QBmwgbKWyyi8F2ZfHMYywqzkaZBdqSVD2opcKzjaaTuAB0l67IDKkoBL9cBeaebW
  Vqow3SzaNfndrNFby2NevtjuWrul2j35p86+ZXcv/FSKwgS9ITw44jQ+LtiYaFdf6iY8hl
  KJ3RCbi1mCQAjJKvT0gOfG8oRh5/sVB6jjz8B1ltAxqx8x8pZsr2QgfJkKKhHCZjK6LD52
  8faSTtKbN53gMLAAAAFWZpbmFuQExBUFRPUC1ROEFQS1BNNwECAwQF
  -----END OPENSSH PRIVATE KEY-----
          script: |
            cd /unipanamericana
            docker-compose stop unipanamericana-app
            docker stop unipanamericana-spring
            docker rm unipanamericana-spring
            docker pull andresmen30/unipanamericana-docker:latest
            docker-compose up -d unipanamericana-app
            docker ps -a

